#!/usr/bin/env bash

#
# This file is part of the Async2 Framework package.
# (c) Petru Szemereczki <petru.office92@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

#
# This file is part of the Async2 Framework package.
# (c) Petru Szemereczki <petru.office92@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

#
# This file is part of the Async2 Framework package.
# (c) Petru Szemereczki <petru.office92@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

#
# This file is part of the Async2 Framework package.
# (c) Petru Szemereczki <petru.office92@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

docker-compose exec php "$@"
